AElf-devops/aelf-website-next

src/pages/api/recentBlogList.ts, src/utils/request.ts
1. Refactor: optimize recentBlogList api. #57
=> Refactor: optimize recentBlogList api

src/pages/index.tsx
1. Adjust landing page meta. #61
=> Adjust landing page meta

src/pageComponents/developer-center/ExploreSection/index.tsx, src/pageComponents/developer-center/LinkList/index.tsx, src/pageComponents/developer-center/LinkList/styles.module.scss, src/pageComponents/developer-center/StartCardSection/index.tsx
1. Feat: adjust text and links on the developer center page. #65
=> Feat: adjust text and links on the developer center page

src/pages/_app.tsx
1. Feat: add canonical link. #71
=> Feat: add canonical link

src/constants/index.ts, src/pageComponents/landing/ExperienceSection/RecentBlogList/index.tsx, src/pageComponents/landing/ExperienceSection/index.tsx, src/pages/_app.tsx, src/pages/developer-center/index.tsx, src/pages/ecosystem/index.tsx, src/pages/index.tsx, src/pages/platform/index.tsx
1. Implement SSG and Improve SEO. #74
=> Implement SSG and Improve SEO

src/components/CommonCard/index.tsx, src/components/CommonFooter/index.tsx, src/components/CommonHeader/index.tsx, src/components/CommonImageTextPart/index.tsx, src/pageComponents/ecosystem/DappsSection/index.tsx, src/pageComponents/ecosystem/OverviewSection/index.tsx, src/pageComponents/ecosystem/VenturesSection/index.tsx, src/pageComponents/landing/ExperienceSection/BlogItem/index.tsx, src/pageComponents/landing/ExperienceSection/RecentBlogList/index.tsx, src/pageComponents/landing/FirstScreenSection/LandingHeroAnimationImage/index.tsx, src/pageComponents/landing/FirstScreenSection/index.tsx, src/pageComponents/landing/FunctionSection/index.tsx, src/pageComponents/landing/ListSection/index.tsx, src/pageComponents/platform/TokenomicsSection/TokenomicsItem/index.tsx, src/pageComponents/platform/TokenomicsSection/index.tsx, src/pages/_document.tsx, src/pages/api/recentBlogList.ts, src/pages/index.tsx, src/styles/globals.scss, src/types/webflow.ts
1. Optimize font loading. #79 
2. Add alt text to images. #77 #78
=> Optimize font loading and add alt text to images

package.json, src/pageComponents/developer-center/DevelopersSection/index.tsx
1. Feat: adjust links on the developer center page. close #87
=> Feat: adjust links on the developer center page

src/pageComponents/developer-center/DevelopersSection/index.tsx, src/pageComponents/developer-center/ExploreSection/index.tsx, src/pageComponents/developer-center/GuideCardSection/index.tsx
1. Adjust text and links on the developer center page. close #96
=> Adjust text and links on the developer center page

src/components/CommonFirstScreenSection/styles.module.scss, src/pageComponents/landing/FirstScreenSection/LandingHero/styles.module.scss
1. Style: adjust animation and font weight.  close #99
=> Style: adjust animation and font weight

src/components/CommonFooter/index.tsx, src/components/CommonHeader/index.tsx, src/components/CommonHeader/styles.module.scss
1. Add header banner and adjust footer link. close #101
=> Add header banner and adjust footer link

src/components/CommonHeader/index.tsx
1. Adjust banner text. close #103
=> Adjust banner text

src/pages/_app.tsx
1. Feat: adjust structured data. #108
=> Feat: adjust structured data

src/components/GoogleTagManager/index.tsx, src/components/Hotjar/index.tsx, src/pageComponents/platform/FirstScreenSection/index.tsx, src/pages/_app.tsx
1. Add hotjar tracking and adjust text. close #110
=> Add hotjar tracking and adjust text

src/components/ChatPAAL/index.tsx, src/components/CommonFooter/index.tsx, src/pages/_app.tsx, src/pages/developer-center/index.tsx, src/pages/ecosystem/index.tsx, src/pages/index.tsx, src/pages/platform/index.tsx
=> Feat: chatPAAL

next.config.mjs, src/components/CommonFooter/index.tsx, src/components/CommonFooter/styles.module.scss, src/components/CommonHeader/index.tsx, src/components/CommonSEOHead/index.tsx, src/constants/index.ts, src/contexts/useConfig/index.tsx, src/pages/_app.tsx, src/pages/developer-center/index.tsx, src/pages/ecosystem/index.tsx, src/pages/index.tsx, src/pages/platform/index.tsx
1. Adjust header and footer, improve meta handling, and add support for image domains. close #114
=> Adjust header and footer, improve meta handling, and add support for image domains

src/components/GoogleAnalytics/index.tsx, src/pages/_app.tsx
1. Feat: replace GA integration from GTM to direct script inclusion. #113
=> Feat: replace GA integration from GTM to direct script inclusion

src/components/CommonSEOHead/index.tsx, src/pages/_app.tsx
1. Feat: implement per-page structured data with description for better SEO. close #118
=> Feat: implement per-page structured data with description for better SEO

src/components/CommonSEOHead/index.tsx, src/constants/index.ts, src/pages/_app.tsx
1. Feat: adjust meta description and add website structured data. close #122
=> Feat: adjust meta description and add website structured data

package.json, src/components/CommonHeader/index.tsx
1. Feat: hide banner. close #129
=> Feat: hide banner

src/pageComponents/platform/TokenomicsSection/TokenomicsDescription/index.tsx, src/pageComponents/platform/TokenomicsSection/TokenomicsDescription/styles.module.scss, src/pageComponents/platform/TokenomicsSection/index.tsx
1. Add tokenomics description. close #131
=> Add tokenomics description

global.d.ts, src/components/Amplitude/index.tsx, src/constants/index.ts
Amplitude session replay. close #136
=> Amplitude session replay

src/pageComponents/developer-center/ExploreSection/index.tsx
Added new tutorials for developer-centre section
=> Feature: Added new tutorials for developer-centre section
